# Titanic Visualization Project (DATA6550)
#### By Jennifer Panula

*Disclaimer: A reasonable portion of this code was used from prior-created code that I had done as part of an assignment last semeseter.*

## Part 1: Data Preprocessing
### Part 1 Section A: 
1. Load both the training dataset (train.csv) and test dataset (test.csv).
2. Separate and preserve the target variable (Survived) from the training set and test set, which can be saved as y train and y test. Combine the training and test datasets for consistent preprocessing while keeping track of which rows belong to training vs. test data.


In [2]:
#Import Initial Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [3]:
# load the data
df_train = pd.read_csv('data/train.csv')
df_test = pd.read_csv('data/tested.csv')

In [4]:
df_train.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [5]:
df_test.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [7]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


In [8]:
y_train = df_train['Survived']
y_train.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [9]:
y_test = df_test['Survived']
y_test.head()

0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

In [10]:
#combining training and test datasets for consistent pre-processing.
df = pd.concat([df_train, df_test], axis = 0)

In [11]:
df[890:893]

PassengerId  Survived  Pclass                              Name     Sex  \
890          891         0       3               Dooley, Mr. Patrick    male   
0            892         0       3                  Kelly, Mr. James    male   
1            893         1       3  Wilkes, Mrs. James (Ellen Needs)  female   

      Age  SibSp  Parch  Ticket    Fare Cabin Embarked  
890  32.0      0      0  370376  7.7500   NaN        Q  
0    34.5      0      0  330911  7.8292   NaN        Q  
1    47.0      1      0  363272  7.0000   NaN        S

In [12]:
df = df.reset_index(drop = True) 

In [13]:
df[890:893]

PassengerId  Survived  Pclass                              Name     Sex  \
890          891         0       3               Dooley, Mr. Patrick    male   
891          892         0       3                  Kelly, Mr. James    male   
892          893         1       3  Wilkes, Mrs. James (Ellen Needs)  female   

      Age  SibSp  Parch  Ticket    Fare Cabin Embarked  
890  32.0      0      0  370376  7.7500   NaN        Q  
891  34.5      0      0  330911  7.8292   NaN        Q  
892  47.0      1      0  363272  7.0000   NaN        S

Taking inventory of where our train/text split lies. Training is indexes 0:890.  Test data is indexes 891:1308. 

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1309 non-null   int64  
 1   Survived     1309 non-null   int64  
 2   Pclass       1309 non-null   int64  
 3   Name         1309 non-null   object 
 4   Sex          1309 non-null   object 
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64  
 7   Parch        1309 non-null   int64  
 8   Ticket       1309 non-null   object 
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object 
 11  Embarked     1307 non-null   object 
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB


### Part 1, Section B:
3. Handle missing values using training data statistics only to avoid data leakage:
   
- Age: Fill missing values with the median age grouped by Pclass and Sex. Calculate the median from training data only, then apply to both training and test sets.
- Fare: Fill missing values with the median fare grouped by Pclass. Use training data statistics only.
- Embarked: Fill missing values with the most common port of embarkation from the training data.
- Cabin: Create a binary feature Has Cabin indicating whether cabin information is available (1) or missing (0), then drop the original Cabin column.


In [15]:
median_age_by_class_and_sex = df_train.groupby(['Pclass', 'Sex'])['Age'].median()
median_age_by_class_and_sex

Pclass  Sex   
1       female    35.0
        male      40.0
2       female    28.0
        male      30.0
3       female    21.5
        male      25.0
Name: Age, dtype: float64

In [16]:
df['Age'] = df['Age'].fillna(
    df[['Pclass','Sex']].apply(tuple, axis=1).map(median_age_by_class_and_sex)
)

In [17]:
median_fares_by_class = df_train.groupby('Pclass')['Fare'].median()
median_fares_by_class

Pclass
1    60.2875
2    14.2500
3     8.0500
Name: Fare, dtype: float64

In [18]:
df['Fare'] = df['Fare'].fillna(df['Pclass'].map(median_fares_by_class))

In [19]:
df_train['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [20]:
df['Embarked'] = df['Embarked'].fillna('S')

In [21]:
df['Embarked'].isna().value_counts()

Embarked
False    1309
Name: count, dtype: int64

In [22]:
df['Has_Cabin'] = (~df['Cabin'].isna()).astype(int)
df['Has_Cabin'].value_counts()

Has_Cabin
0    1014
1     295
Name: count, dtype: int64

In [23]:
df = df.drop('Cabin', axis = 1)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1309 non-null   int64  
 1   Survived     1309 non-null   int64  
 2   Pclass       1309 non-null   int64  
 3   Name         1309 non-null   object 
 4   Sex          1309 non-null   object 
 5   Age          1309 non-null   float64
 6   SibSp        1309 non-null   int64  
 7   Parch        1309 non-null   int64  
 8   Ticket       1309 non-null   object 
 9   Fare         1309 non-null   float64
 10  Embarked     1309 non-null   object 
 11  Has_Cabin    1309 non-null   int64  
dtypes: float64(2), int64(6), object(4)
memory usage: 122.8+ KB


### Part 1, Secion C:
 4. Feature Engineering- Create new predictive features:
- Extract Title from the Name column using regular expression r’ ([A-Za-z]+)\.’ (e.g., Mr, Mrs, Miss, Master).
- Group rare titles (Lady, Countess, Capt, Col, Don, Dr, Major, Rev, Sir, Jonkheer, Dona) into a single category called ’Rare’.
- Standardize similar titles: ’Mlle’ → ’Miss’, ’Ms’ → ’Miss’, ’Mme’ → ’Mrs’.
- Create FamilySize = SibSp + Parch + 1.
- Create IsAlone as a binary indicator (1 if FamilySize = 1, otherwise 0).


In [25]:
df['Title'] = df['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)

In [26]:
# Normalize alternate versions
df['Title'] = df['Title'].replace({
    'Mlle': 'Miss',
    'Ms': 'Miss',
    'Mme': 'Mrs'
})

# Group rare titles
rare_titles = ['Capt', 'Col', 'Countess', 'Don', 'Dona', 'Dr', 'Jonkheer',
               'Lady', 'Major', 'Rev', 'Sir']

df['Title'] = df['Title'].replace(rare_titles, 'Rare')

In [27]:
df['Title'].value_counts()

Title
Mr        757
Miss      264
Mrs       198
Master     61
Rare       29
Name: count, dtype: int64

In [28]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['FamilySize'].value_counts()

FamilySize
1     790
2     235
3     159
4      43
6      25
5      22
7      16
11     11
8       8
Name: count, dtype: int64

In [29]:
df['IsAlone'] = (df['FamilySize'] == 1).astype(int)
df['IsAlone'].value_counts()

IsAlone
1    790
0    519
Name: count, dtype: int64

### Part 1, Section D:
5. Encode categorical features into numerical format:
- Convert Sex to binary values using mapping: male = 0, female = 1.
- Applyone-hot encoding to Embarked and Title using pd.get_dummies with drop_first = True parameter to avoid multicollinearity.
- Note: homework directions doesn't specify, but I also encoded "PClass" 
 6. Remove columns that are not useful for prediction: PassengerId, Name, Ticket, and Cabin.
- Note: homework directions didn't specify, but I also dropped SibSp and Parch since they were used to calculate another column, I figured they would be redundant. 

In [30]:
#converting sex to binary
gender_mapping = {'male': 0, 'female': 1}

# Apply the mapping to the 'Sex' column
df['Sex'] = df['Sex'].map(gender_mapping)

In [31]:
df['Sex'].value_counts()

Sex
0    843
1    466
Name: count, dtype: int64

In [32]:
#encoding embarked
embarked_dummies = pd.get_dummies(df['Embarked'], drop_first = True, dtype = int, prefix='Embarked')
df = pd.concat([df, embarked_dummies], axis = 1)

In [33]:
#encoding title
title_dummies = pd.get_dummies(df['Title'], drop_first = True, dtype = int, prefix='Title')
df = pd.concat([df, title_dummies], axis = 1)

In [34]:
#looks like this also may benefit from encoding
df['Pclass'].value_counts()

Pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [35]:
#encoding Pclass
class_dummies = pd.get_dummies(df['Pclass'], drop_first = True, dtype = int, prefix='Class')
df = pd.concat([df, class_dummies], axis = 1)

In [36]:
#removing not-useful columns. ('Cabin' already dropped in part B). 
df = df.drop(['PassengerId', 'Name', 'Ticket', 'Embarked', 'Title', 'Pclass', 'SibSp', 'Parch'], axis = 1)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Survived    1309 non-null   int64  
 1   Sex         1309 non-null   int64  
 2   Age         1309 non-null   float64
 3   Fare        1309 non-null   float64
 4   Has_Cabin   1309 non-null   int64  
 5   FamilySize  1309 non-null   int64  
 6   IsAlone     1309 non-null   int64  
 7   Embarked_Q  1309 non-null   int64  
 8   Embarked_S  1309 non-null   int64  
 9   Title_Miss  1309 non-null   int64  
 10  Title_Mr    1309 non-null   int64  
 11  Title_Mrs   1309 non-null   int64  
 12  Title_Rare  1309 non-null   int64  
 13  Class_2     1309 non-null   int64  
 14  Class_3     1309 non-null   int64  
dtypes: float64(2), int64(13)
memory usage: 153.5 KB


In [38]:
df_titanic_cleansed = df.copy()

In [39]:
# Export to CSV to try to create visualizations with different software
# try:
#     df_titanic_cleansed.to_csv("titanic_cleansed.csv", index=False)
#     print("Data successfully exported to output.csv")
# except Exception as e:
#     print(f"Error writing CSV: {e}")

Data successfully exported to output.csv


In [37]:
X_train_clean = df[0:891].drop('Survived', axis = 1)
X_test_clean = df[891:1309].drop('Survived', axis = 1)

In [38]:
X_train_clean.tail()

Sex   Age   Fare  Has_Cabin  FamilySize  IsAlone  Embarked_Q  Embarked_S  \
886    0  27.0  13.00          0           1        1           0           1   
887    1  19.0  30.00          1           1        1           0           1   
888    1  21.5  23.45          0           4        0           0           1   
889    0  26.0  30.00          1           1        1           0           0   
890    0  32.0   7.75          0           1        1           1           0   

     Title_Miss  Title_Mr  Title_Mrs  Title_Rare  Class_2  Class_3  
886           0         0          0           1        1        0  
887           1         0          0           0        0        0  
888           1         0          0           0        0        1  
889           0         1          0           0        0        0  
890           0         1          0           0        0        1

In [39]:
X_test_clean.head()

Sex   Age     Fare  Has_Cabin  FamilySize  IsAlone  Embarked_Q  \
891    0  34.5   7.8292          0           1        1           1   
892    1  47.0   7.0000          0           2        0           0   
893    0  62.0   9.6875          0           1        1           1   
894    0  27.0   8.6625          0           1        1           0   
895    1  22.0  12.2875          0           3        0           0   

     Embarked_S  Title_Miss  Title_Mr  Title_Mrs  Title_Rare  Class_2  Class_3  
891           0           0         1          0           0        0        1  
892           1           0         0          1           0        0        1  
893           0           0         1          0           0        1        0  
894           1           0         1          0           0        0        1  
895           1           0         0          1           0        0        1

In [40]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler


In [41]:
#data scaling (only of the numerical items, not the binary items, per instructions) 

# Define the features to be scaled
features_to_scale = ['Age', 'Fare', 'FamilySize']

# Create a ColumnTransformer
# The 'remainder="passthrough"' argument ensures that columns not specified in transformers are kept as they are.
preprocess = ColumnTransformer(
    transformers=[
        ('scaler', StandardScaler(), features_to_scale)
    ],
    remainder='passthrough'
)

# Fit only on training data
preprocess.fit(X_train_clean)

# Transform both
X_train_scaled = preprocess.transform(X_train_clean)
X_test_scaled  = preprocess.transform(X_test_clean)